language: node_js
node_js:
  - 10
  - 8
  - 6
before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8