language: node_js
node_js:
  - "4.2"
  - "0.12"
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - pip install codecov
after_success:
  - codecov