// Autogenerated, do not edit. All changes will be lost.

/// <reference path="../node_modules/streamline-node/streamline-node.d.ts" />
/// <reference path="../node_modules/streamline-runtime/lib/streamline-runtime.d.ts" />